## 2.1 Juliaの基本

### 2.1.1 変数
変数の代入

In [1]:
x = 1

1

REPLと同様ansに値が入る

In [2]:
ans

1

乗算記号なしで数式を記述することも可能

In [4]:
2x+1

3

unicodeを変数名に利用可能  
"θ"は，REPL上だと"\theta"の後にTabキーで出る．Jupyter notebookだと使えないので日本語でθと打つ

In [7]:
θ = pi/4
sin(θ)+cos(θ)

1.414213562373095

### 2.1.2 プリミティブ型

In [9]:
typeof(0.5)

Float64

16進は他の言語同様0xXXと表記する  
2進も同様に0bXX

In [11]:
0xa*0xb

0x6e

### 2.1.3 任意精度演算
科学技術計算向きの言語らしく，標準で任意精度演算BigInt, BigFloatがある

In [13]:
typeof(12345678901234567890123456789012345678901234567890)

BigInt

BigFloatは勝手にFloat64に丸められてしまう．  
BigFloatの変数を作るときはperseを使う

In [14]:
typeof(0.1234567890123456789012345678901234567890)

Float64

In [15]:
typeof(parse(BigFloat, "0.1234567890123456789012345678901234567890"))

BigFloat

### 2.1.4 定数
定数は以下のようにconstという宣言をつける．既に使用してしまった値は定数にできない．

In [16]:
const y=1.0

1.0

予め決められた定数もある

In [17]:
π

π = 3.1415926535897...

### 2.1.5 基本的な演算子
演算子は他の言語同様．優先度は()のような形で，乗算，除算，べき乗が優先される．

In [18]:
x = (1 + 2 - ((3 * 4) / 5)) % (6 ^ 7)

0.6000000000000001

べき乗に"^"があるのが便利な反面，xorには使えないので，xorは"⊻"(排他的論理和の数学記号)を使う．"⊻"は変換だと出てこない．REPLなら"\xor" + Tab出でるが，JupyterだとU+22BBと打って変換するか辞書登録するしかなさそう

In [19]:
0b0101 ⊻ 0b1010

0x0f

書きにくい場合こっちのほうが手っ取り早いかもしれない

In [21]:
xor(0b0101, 0b1010)

0x0f

### 2.1.6 更新演算子

In [22]:
x += 10

10.6

### 2.1.7 複素数

In [23]:
x = 1 + 0.5im

1.0 + 0.5im

実数部と虚数部を出力するには以下  

In [24]:
println("Re = " * string(real(x)))
println(string("Im = ", imag(x)))

Re = 1.0
Im = 0.5


### 2.1.8～10 文字列
文字列は""でくくる．文字列への変換はstring(), 文字列結合は"*"を使う．str[3]のように，文字列のうち1文字のCharを取り出すことも可能．

In [25]:
str = "test string"
str[3]

's': ASCII/Unicode U+0073 (category Ll: Letter, lowercase)

ただしマルチバイト文字は文字の順番とindexが合わなくなる．

In [28]:
str2 = "テスト文字列"
str2[4]

'ス': Unicode U+30B9 (category Lo: Letter, other)

こういう場合はcharの配列に変換すると文字とindexが合う用になる．

In [29]:
chars = Vector{Char}(str2)
chars[2]

'ス': Unicode U+30B9 (category Lo: Letter, other)

文字列の他の関数として，python同様にreplaceやsplitが用意されている．含むかは，"in"ではなくoccursin

In [37]:
println(length("Hello")) # 長さ
println(replace(str, "test" => "main")) # 変換
println(split(str, " ")) # 分割
println(occursin("he", "hello")) # xにyを含むか

5
main string
SubString{String}["test", "string"]
true


## 2.6 多次元配列
### 2.6.3 インデクシング
配列の取り扱いはMATLABに似ている．要素抽出にはコロン":"や"end"が使える．また，indexはMATLABと同様1始まり．

In [38]:
println(str[1:5])
println(str[6:end])

test 
string


### 2.6.1 初期化, 2.6.2 基本的な操作
標準が多次元配列を示す．初期化にはzeros, ones, randなどが使える．

In [46]:
A = ones(3, 4)
println(A)
println(size(rand(4, 3)))

[1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0]
(4, 3)


In [47]:
B = rand(4, 3)

4×3 Array{Float64,2}:
 0.617405  0.528379   0.485967
 0.759446  0.850579   0.267906
 0.312274  0.0977961  0.930961
 0.22509   0.776556   0.64871

### 2.6.4 多次元配列の演算
MATLAB同様，多次元配列を通常の演算子で四則演算できる．ドットで要素単位の計算も可能．転置行列は"'"．

In [52]:
A * B

3×3 Array{Float64,2}:
 1.91421  2.25331  2.33354
 1.91421  2.25331  2.33354
 1.91421  2.25331  2.33354

In [53]:
A .+ B'

3×4 Array{Float64,2}:
 1.6174   1.75945  1.31227  1.22509
 1.52838  1.85058  1.0978   1.77656
 1.48597  1.26791  1.93096  1.64871

### 2.6.5 ブロードキャスティング
サイズが異なる配列への演算がドットで可能

In [57]:
A .+ B[:,1]'

3×4 Array{Float64,2}:
 1.6174  1.75945  1.31227  1.22509
 1.6174  1.75945  1.31227  1.22509
 1.6174  1.75945  1.31227  1.22509

関数定義に対しても同様に適用可能．

In [63]:
square(x) = x * x;
square(10)

100

In [66]:
square(A) # ブロードキャスティングしないと実行できない

LoadError: DimensionMismatch("A has dimensions (3,4) but B has dimensions (3,4)")

In [67]:
square.(A) # 関数の後にドットを打つことでブロードキャスティングされる

3×4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

### 2.6.6. map reduce filter
配列要素に関数を適用したり集約する場合はこれらの関数を利用するのが便利．

In [72]:
map(x -> x*x, B)

4×3 Array{Float64,2}:
 0.381189   0.279185    0.236164
 0.576758   0.723485    0.0717738
 0.0975151  0.00956408  0.866688
 0.0506654  0.603039    0.420825

In [74]:
filter(x -> x<0.1, B)

1-element Array{Float64,1}:
 0.09779611559607782

ただし，上記は別の記載も可能．使いやすいものを使うと良さそう．

In [76]:
[x*x for x in B] # リスト内包表記でもいける．

4×3 Array{Float64,2}:
 0.381189   0.279185    0.236164
 0.576758   0.723485    0.0717738
 0.0975151  0.00956408  0.866688
 0.0506654  0.603039    0.420825

In [77]:
B[B.<0.1] # 条件を満たすindexで抽出することも可能．

1-element Array{Float64,1}:
 0.09779611559607782

配列については公式ドキュメントの他，以下のQiita記事も参考になる．  
[Juliaで最低限やっていくための配列操作まとめ - Qiita](https://qiita.com/A03ki/items/007be353411d19952ef7)  